- type: web
    name: flask-messenger
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python api/index.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_SECRET_KEY
        generateValue: true
=======
services:
  - type: web
    name: flask-messenger
    runtime: python3
    buildCommand: pip install -r requirements.txt
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_SECRET_KEY
        generateValue: true
